---
# Ansible playbook to set up or update my home directory and related stuff on macOS.
# On Linux this is done with Puppet.

- hosts: macos
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          - diff-so-fancy
          - git
          - gnupg
          - keychain
          - pinentry-mac
          - vim
          - zsh-autosuggestions
          - zsh-completions
          - zsh-syntax-highlighting
        state: latest

    - name: Clone or update repos
      ansible.builtin.git:
        repo: git@gitlab.com:kenyon/{{ item }}.git
        dest: '{{ ansible_user_dir }}/git/{{ item }}'
        update: yes
      loop:
        - sysadmin
        - dotfiles
        - scripts

    - name: Create ~/.ssh
      ansible.builtin.file:
        state: directory
        mode: '0700'
        path: '{{ ansible_user_dir }}/.ssh'

    - name: Create other directories
      ansible.builtin.file:
        state: directory
        recurse: yes
        path: '{{ ansible_user_dir }}/{{ item }}'
      loop:
        - .config/git

    - name: Create symlinks to dotfiles
      ansible.builtin.file:
        state: link
        force: yes
        path: '{{ ansible_user_dir }}/{{ item }}'
        src: '{{ ansible_user_dir }}/git/dotfiles/{{ item }}'
      loop:
        - .aspell.en.prepl
        - .aspell.en.pws
        - .config/git/ignore
        - .emacs.d
        - .gitconfig
        - .inputrc
        - .profile
        - .screenrc
        - .signature
        - .tmux.conf
        - .vim
        - .vimrc
        - .zlogin
        - .zshenv
        - .zshrc

    - name: Create vim-gnupg directories
      ansible.builtin.file:
        state: directory
        recurse: yes
        path: '{{ ansible_user_dir }}/.vim/pack/gnupg/start'

    - name: Clone or update vim-gnupg
      ansible.builtin.git:
        repo: git@github.com:jamessan/vim-gnupg.git
        dest: '{{ ansible_user_dir }}/.vim/pack/gnupg/start/vim-gnupg'
        update: yes

    - name: Set secure directory permissions to allow zsh to load completions
      ansible.builtin.file:
        path: /usr/local/share
        recurse: yes
        mode: go-w
