---
# Ansible playbook to set up or update my home directory and related stuff.

- name: Homedir setup
  hosts: all
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          - diff-so-fancy
          - git
          - gnupg
          - keychain
          - pinentry-mac
          - vim
          - zsh-autosuggestions
          - zsh-completions
          - zsh-syntax-highlighting
        state: installed
      when: ansible_facts.os_family == 'Darwin'

    - name: Create my git repo directory
      ansible.builtin.import_tasks: tasks/ensure-git-dir.yaml
    - name: Update my git repos
      ansible.builtin.import_tasks: tasks/update-sysadmin-repos.yaml

    - name: Create ~/.ssh and ~/.gnupg
      ansible.builtin.file:
        state: directory
        mode: "0700"
        path: "{{ ansible_user_dir }}/{{ item }}"
      loop:
        - .gnupg
        - .ssh

    - name: Create other directories
      ansible.builtin.file:
        state: directory
        recurse: true
        path: "{{ ansible_user_dir }}/{{ item }}"
      loop:
        - .config/git

    - name: Create symlinks to dotfiles
      ansible.builtin.file:
        state: link
        force: true
        path: "{{ ansible_user_dir }}/{{ item }}"
        src: "{{ ansible_user_dir }}/git/dotfiles/{{ item }}"
      loop:
        - .aspell.en.prepl
        - .aspell.en.pws
        - .config/git/ignore
        - .emacs.d
        - .gitconfig
        - .inputrc
        - .profile
        - .screenrc
        - .signature
        - .tmux.conf
        - .vim
        - .vimrc
        - .zlogin
        - .zshenv
        - .zshrc
      when: ansible_facts.os_family == 'Darwin'

    - name: Create symlinks to more dotfiles
      ansible.builtin.file:
        state: link
        force: true
        path: "{{ ansible_user_dir }}/{{ item }}"
        src: "{{ ansible_user_dir }}/git/sysadmin/dotfiles/{{ item }}"
      loop:
        - .gnupg/gpg-agent.conf
        - .gnupg/gpg.conf

    - name: Create vim-gnupg directories
      ansible.builtin.file:
        state: directory
        recurse: true
        path: "{{ ansible_user_dir }}/.vim/pack/gnupg/start"

    - name: Clone or update vim-gnupg # noqa: latest
      ansible.builtin.git:
        repo: git@github.com:jamessan/vim-gnupg.git
        dest: "{{ ansible_user_dir }}/.vim/pack/gnupg/start/vim-gnupg"
        update: true

    - name: Set secure directory permissions to allow zsh to load completions
      ansible.builtin.file:
        path: /usr/local/share
        recurse: true
        mode: go-w
      when: ansible_facts.os_family == 'Darwin'
