---
# Ansible playbook to set up or update my home directory and related stuff.

- hosts: all
  tasks:
    # FIXME: remove this task once I'm managing ssh_known_hosts with puppet.
    - name: Update ssh_known_hosts
      become: yes
      known_hosts:
        path: /etc/ssh/ssh_known_hosts
        name: '{{ item.names[0] }}'
        key: '{{ item.names|join(",") }} {{ item.key }}'
      loop: '{{ ssh_known_hosts }}'

    - name: Update sysadmin repo
      git:
        repo: darwin.kenyonralph.com:git/sysadmin.git
        dest: '{{ ansible_facts.env.HOME }}/git/sysadmin'
        update: yes

    - name: Clone or update dotfiles repo from github
      git:
        repo: git@github.com:kenyon/dotfiles.git
        dest: '{{ ansible_facts.env.HOME }}/git/dotfiles'
        update: yes

    - name: Create ~/.ssh
      file:
        state: directory
        mode: '0700'
        path: '{{ ansible_facts.env.HOME }}/.ssh'

    - name: Create other directories
      file:
        state: directory
        recurse: yes
        path: '{{ ansible_facts.env.HOME }}/{{ item }}'
      loop:
        - .config/git
        - .emacs.d
        - .vim

    - name: Create symlinks to dotfiles
      file:
        state: link
        force: yes
        path: '{{ ansible_facts.env.HOME }}/{{ item }}'
        src: '{{ ansible_facts.env.HOME }}/git/dotfiles/{{ item }}'
      loop:
        - .aspell.en.prepl
        - .aspell.en.pws
        - .bash_aliases
        - .bash_profile
        - .bashrc
        - .config/git/ignore
        - .devscripts
        - .dput.cf
        - .emacs.d
        - .gitconfig
        - .inputrc
        - .profile
        - .quiltrc
        - .screenrc
        - .signature
        - .ssh/config
        - .tmux.conf
        - .toprc
        - .vim
        - .vimrc
        - .zlogin
        - .zshenv
        - .zshrc

...
