---
# Ansible playbook to set up or update my home directory and related stuff.

# FIXME: all of this should be managed with puppet instead. remove
# this playbook once I have puppet managing these things.

- hosts: all
  tasks:
    - name: Update ssh_known_hosts
      become: yes
      known_hosts:
        path: /etc/ssh/ssh_known_hosts
        name: '{{ item.names[0] }}'
        key: '{{ item.names|join(",") }} {{ item.key }}'
      loop: '{{ ssh_known_hosts }}'

    - name: Ensure git is installed
      become: '{{ "yes" if ansible_facts.os_family != "Darwin" }}' # homebrew shall not run as root
      package:
        name: git
        state: latest

    - name: Clone or update sysadmin repo
      git:
        repo: git@gitlab.com:kenyon/sysadmin.git
        dest: '{{ ansible_user_dir }}/git/sysadmin'
        update: yes

    - name: Clone or update dotfiles repo
      git:
        repo: git@gitlab.com:kenyon/dotfiles.git
        dest: '{{ ansible_user_dir }}/git/dotfiles'
        update: yes

    - name: Clone or update scripts repo
      git:
        repo: git@gitlab.com:kenyon/scripts.git
        dest: '{{ ansible_user_dir }}/git/scripts'
        update: yes

    - name: Create ~/.ssh
      file:
        state: directory
        mode: '0700'
        path: '{{ ansible_user_dir }}/.ssh'

    - name: Create other directories
      file:
        state: directory
        recurse: yes
        path: '{{ ansible_user_dir }}/{{ item }}'
      loop:
        - .config/git
        - .emacs.d
        - .vim

    - name: Create other directories (einstein)
      when: inventory_hostname == 'einstein'
      file:
        state: directory
        recurse: yes
        path: '{{ ansible_user_dir }}/{{ item }}'
      loop:
        - .xmonad

    - name: Create symlinks to dotfiles
      file:
        state: link
        force: yes
        path: '{{ ansible_user_dir }}/{{ item }}'
        src: '{{ ansible_user_dir }}/git/dotfiles/{{ item }}'
      loop:
        - .aspell.en.prepl
        - .aspell.en.pws
        - .bash_aliases
        - .bash_profile
        - .bashrc
        - .config/git/ignore
        - .devscripts
        - .dput.cf
        - .emacs.d
        - .gitconfig
        - .inputrc
        - .profile
        - .quiltrc
        - .screenrc
        - .signature
        - .tmux.conf
        - .toprc
        - .vim
        - .vimrc
        - .zlogin
        - .zshenv
        - .zshrc

    - name: Create symlinks to dotfiles (einstein)
      when: inventory_hostname == 'einstein'
      file:
        state: link
        force: yes
        path: '{{ ansible_user_dir }}/{{ item }}'
        src: '{{ ansible_user_dir }}/git/dotfiles/hosts/einstein/{{ item }}'
      loop:
        - .Xmodmap
        - .mailcap
        - .xmobarrc
        - .xmonad/xmonad.hs
        - .xsession

...
