---
# Ansible playbook to set up or update my home directory and related stuff on macOS.
# On Linux this is done with Puppet.

- hosts: macos
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          - diff-so-fancy
          - git
          - gnupg
          - keychain
          - pinentry-mac
          - zsh-syntax-highlighting
        state: latest

    - name: Clone or update sysadmin repo
      ansible.builtin.git:
        repo: git@gitlab.com:kenyon/sysadmin.git
        dest: '{{ ansible_user_dir }}/git/sysadmin'
        update: yes

    - name: Clone or update dotfiles repo
      ansible.builtin.git:
        repo: git@gitlab.com:kenyon/dotfiles.git
        dest: '{{ ansible_user_dir }}/git/dotfiles'
        update: yes

    - name: Clone or update scripts repo
      ansible.builtin.git:
        repo: git@gitlab.com:kenyon/scripts.git
        dest: '{{ ansible_user_dir }}/git/scripts'
        update: yes

    - name: Create ~/.ssh
      ansible.builtin.file:
        state: directory
        mode: '0700'
        path: '{{ ansible_user_dir }}/.ssh'

    - name: Create other directories
      ansible.builtin.file:
        state: directory
        recurse: yes
        path: '{{ ansible_user_dir }}/{{ item }}'
      loop:
        - .config/git
        - .emacs.d
        - .vim/pack/gnupg/start

    - name: Clone or update vim-gnupg
      ansible.builtin.git:
        repo: git@github.com:jamessan/vim-gnupg.git
        dest: '{{ ansible_user_dir }}/.vim/pack/gnupg/start/vim-gnupg'
        update: yes

    - name: Create symlinks to dotfiles
      ansible.builtin.file:
        state: link
        force: yes
        path: '{{ ansible_user_dir }}/{{ item }}'
        src: '{{ ansible_user_dir }}/git/dotfiles/{{ item }}'
      loop:
        - .aspell.en.prepl
        - .aspell.en.pws
        - .config/git/ignore
        - .emacs.d
        - .gitconfig
        - .inputrc
        - .profile
        - .screenrc
        - .signature
        - .tmux.conf
        - .vim
        - .vimrc
        - .zlogin
        - .zshenv
        - .zshrc
