---
# Ansible playbook for initial setup of a generic new machine.
# To run:
# ansible-playbook --limit <hostname> --vault-id ~/.ansible/vault-password --become --verbose ~/git/ansible-kenyon/initial-setup.yml

- hosts: all
  tasks:
    - import_role:
        name: common
    - import_role:
        name: puppet-agent

...
