---
# Ansible playbook for initial setup of a new machine.
# To run:
# ansible-playbook --limit <hostname> --become --verbose initial-setup.yml

# For initial setup of a Linode or Vultr VM, use --user root.

- hosts: all,!macos,!localhost
  tasks:
    - include_role:
        name: '{{ grp }}'
      when: grp in group_names
      loop:
        - linode
        - vultr
      loop_control:
        loop_var: grp
    - import_role:
        name: common
    - import_role:
        name: puppet-agent
    - import_role:
        name: puppetserver
      when: "'puppetserver' in group_names"

...
