---
# Ansible playbook for initial setup of a new machine.
# To run:
# ansible-playbook --limit <hostname> --become --verbose initial-setup.yml

# For initial setup of a Linode or Vultr VM, use --user root.

- hosts: all:!macos
  tasks:
    - include_role:
        name: '{{ item }}'
      when: item in group_names
      loop:
        - linode
        - vultr
    - import_role:
        name: common
    - import_role:
        name: puppet-agent
    - import_role:
        name: puppetserver
      when: "'puppetserver' in group_names"

...
