---
# Ansible playbook for initial setup of a new machine.
# To run:
# ansible-playbook --limit <hostname> --become --verbose initial-setup.yml

# For initial setup of a Linode or Vultr VM, use --user root.

- name: Initial setup
  hosts: all,!macos,!localhost
  tasks:
    - name: Import VPS provider role
      ansible.builtin.include_role:
        name: "{{ grp }}"
      when: grp in group_names
      loop:
        - linode
        - vultr
      loop_control:
        loop_var: grp

    - name: Import common role
      ansible.builtin.import_role:
        name: common

    - name: Import puppet-agent role
      ansible.builtin.import_role:
        name: puppet_agent

    - name: Import puppetserver role
      ansible.builtin.import_role:
        name: puppetserver
      when: "'puppetserver' in group_names"
