---
# Ansible playbook for initial setup of a new machine.
# To run:
# ansible-playbook --limit <hostname> --become --verbose ~/git/ansible-kenyon/initial-setup.yml

# For initial setup of a Vultr VM, use --user root.

- hosts: all
  tasks:
    - import_role:
        name: vultr
      when: "'vultr' in group_names"
    - import_role:
        name: common
    - import_role:
        name: puppet-agent
    - import_role:
        name: puppetserver
      when: "'puppetserver' in group_names"

...
