---
# The terminfo that comes with macOS is too old, and doesn't contain
# tmux-256color. So sshing to macOS from my Linux machine which uses
# tmux-256color results in a useless terminal. This playbook ensures
# that terminfo is available using newer ncurses installed from brew.

# Reference: https://unix.stackexchange.com/a/410383/8945

- hosts: macos
  tasks:
    - name: Ensure ~/.terminfo directory exists
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.terminfo"
        state: directory
        mode: 0755

    - name: Ensure ncurses is installed from brew
      community.general.homebrew:
        name: ncurses
        state: latest

    - name: Get ncurses installation location
      ansible.builtin.command: brew --prefix ncurses
      register: brew_prefix_ncurses
      changed_when: false

    - name: Create temporary file to store terminfo source
      ansible.builtin.tempfile:
      register: tempfile

    - name: Decompile terminfo
      ansible.builtin.shell: "{{ brew_prefix_ncurses.stdout }}/bin/infocmp tmux-256color > {{ tempfile.path }}"

    - name: Compile terminfo with system tic
      ansible.builtin.command: tic -s {{ tempfile.path }}

    - name: Remove temporary file
      ansible.builtin.file:
        state: absent
        path: "{{ tempfile.path }}"
