---
# Ansible playbook to prepare to upgrade Debian.
# This doesn't actually do the upgrade because I want to do that
# manually to manually update config files, etc.

- hosts: all
  become: yes
  vars:
    old_release: buster
    new_release: bullseye
  tasks:
    - block:
        - name: Disable puppet agent
          ansible.builtin.command: puppet agent --disable
          # Continue even if puppet isn't installed.
          ignore_errors: yes

        - name: Find sources files
          ansible.builtin.find:
            paths: /etc/apt
            recurse: yes
            patterns: "*.list"
          register: sources

        - name: Replace release codename in sources files
          ansible.builtin.replace:
            regexp: "{{ old_release }}"
            replace: "{{ new_release }}"
            path: "{{ item.path }}"
          loop: "{{ sources.files }}"

        - name: Update package cache
          ansible.builtin.apt:
            update_cache: yes
            autoclean: yes

        - name: Done
          ansible.builtin.debug:
            msg:
              - "Now, the manual upgrade process: apt-get upgrade; apt full-upgrade"
              - "Reference: https://www.debian.org/releases/{{ new_release }}/amd64/release-notes/ch-upgrading.en.html"
      when:
        - ansible_facts['distribution'] == 'Debian'
        - ansible_facts['distribution_release'] == old_release
# Local Variables:
# coding: utf-8
# End:
