---
# Ansible playbook for initial setup of a puppetserver.
# To run:
# ansible-playbook --inventory hostname_or_IP_address, --become --ask-become-pass --verbose ~/git/ansible-kenyon/puppetserver.yml

- hosts: all
  tasks:
    - import_role:
        name: common
    - import_role:
        name: puppet-agent
    - import_role:
        name: puppetserver

...
