- name: Clone or update repos
  ansible.builtin.git:
    repo: git@gitlab.com:kenyon/{{ item }}.git
    dest: "{{ ansible_user_dir }}/git/{{ item }}"
    update: yes
  loop:
    - dotfiles
    - scripts
    - sysadmin
