---
# Tasks for a brand new Debian 10 IPv6-only Vultr VM.

- name: Create swap file
  ansible.builtin.command:
    cmd: dd if=/dev/zero of=/swap bs=1M count=1024
    creates: /swap
  register: create_swap

- name: Set swap file permissions
  ansible.builtin.file:
    path: /swap
    mode: "0600"

- name: Set up swap file
  ansible.builtin.command: mkswap /swap
  changed_when: true

- name: Activate swap file
  ansible.builtin.command: swapon /swap
  changed_when: true

- name: Ensure swap file is in /etc/fstab
  ansible.posix.mount:
    src: /swap
    path: none
    fstype: swap
    opts: sw
    state: present

- name: Remove legacy IP configuration
  ansible.builtin.lineinfile:
    path: /etc/network/interfaces
    regexp: 'iface [\w]+ inet '
    state: absent

# I want to use DNS for FQDN hostname resolution,
# so remove the 127.0.1.1 entry from /etc/hosts.
- name: Configure /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: 127\.0\.1\.1
    state: absent

- name: Configure /etc/resolv.conf
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    line: "{{ item }}"
  loop:
    - search jellardralph.com
    - options edns0

- name: Remove settings Vultr added (I think)
  ansible.posix.sysctl:
    name: "{{ item }}"
    state: absent
  loop:
    - net.core.default_qdisc
    - net.ipv4.tcp_congestion_control
    - net.ipv6.conf.all.accept_ra

- name: Remove some packages
  when: ansible_facts.os_family == 'Debian'
  ansible.builtin.apt:
    name:
      - mdadm
      - rdnssd
      - rsyslog
    state: absent
    purge: true
