---
# Tasks for a brand new Debian 10 IPv6-only Vultr VM.

- name: Create swap file
  command:
    cmd: dd if=/dev/zero of=/swap bs=1M count=1024
    creates: /swap
  register: create_swap

- name: Set swap file permissions
  file:
    path: /swap
    mode: 0600

- name: Set up swap file
  command: mkswap /swap
  when: create_swap is changed

- name: Activate swap file
  command: swapon /swap
  when: create_swap is changed

- name: Ensure swap file is in /etc/fstab
  mount:
    src: /swap
    path: none
    fstype: swap
    opts: sw
    state: present

- name: Remove legacy IP configuration
  lineinfile:
    path: /etc/network/interfaces
    regexp: 'iface [\w]+ inet '
    state: absent

# I want to use DNS for FQDN hostname resolution,
# so remove the 127.0.1.1 entry from /etc/hosts.
- name: Configure /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: 127\.0\.1\.1
    state: absent

- name: Configure /etc/resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    line: '{{ item }}'
  loop:
    - search kenyonralph.com
    - options edns0

- name: Remove some packages
  when: ansible_facts.os_family == 'Debian'
  apt:
    name:
      - mdadm
      - rdnssd
      - rsyslog
    state: absent
    purge: yes

...
