---
# Ansible role to perform common initial setup activities.

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname_short }}"

- name: Create kenyon account
  ansible.builtin.user:
    name: kenyon
    groups:
      - adm
      - sudo
    append: true

- name: Configure my sudo privileges
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "kenyon ALL = (ALL:ALL) NOPASSWD: ALL"
    validate: /usr/sbin/visudo --check --file %s

- name: Set my authorized SSH key
  ansible.posix.authorized_key:
    user: kenyon
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

- name: Lock root password
  ansible.builtin.user:
    name: root
    password_lock: true

- name: Remove some packages
  when: ansible_facts.os_family == 'Debian'
  ansible.builtin.apt:
    name:
      - exim4*
      - nano
    state: absent
    purge: true

- name: Install some packages
  when: ansible_facts.os_family == 'Debian'
  ansible.builtin.apt:
    update_cache: true
    name:
      - aptitude
      - etckeeper
      - python3-apt
      - wget2
