---
# Ansible role to perform common initial setup activities.

- name: Set hostname
  hostname:
    name: '{{ inventory_hostname }}'

- name: Create kenyon account
  user:
    name: kenyon
    groups:
      - sudo
    append: yes

- name: Configure my sudo privileges
  lineinfile:
    path: /etc/sudoers
    line: 'kenyon ALL = (ALL:ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo --check --file %s

- name: Set my authorized SSH key
  authorized_key:
    user: kenyon
    key: "{{ lookup('file', '/home/kenyon/.ssh/id_ed25519.pub') }}"

- name: Lock root password
  user:
    name: root
    password_lock: yes

- name: Remove some packages
  when: ansible_facts.os_family == 'Debian'
  apt:
    name:
      - exim4*
      - nano
      - resolvconf
    state: absent
    purge: yes

- name: Install some packages
  when: ansible_facts.os_family == 'Debian'
  apt:
    update_cache: yes
    name:
      - aptitude
      - etckeeper
      - python-apt
      - python3-apt
      - wget

...
