---
# Ansible role to perform common initial setup activities.

- name: Install packages
  when: ansible_facts.os_family == 'Debian'
  apt:
    name:
      - aptitude
      - etckeeper
      - python-apt
      - python3-apt
      - wget

...
