---
# Ansible role to perform common initial setup activities.

- name: Remove some packages
  when: ansible_facts.os_family == 'Debian'
  apt:
    name:
      - exim4*
      - nano
      - resolvconf
    state: absent
    purge: yes

- name: Install some packages
  when: ansible_facts.os_family == 'Debian'
  apt:
    name:
      - aptitude
      - etckeeper
      - python-apt
      - python3-apt
      - wget

...
